# Generated by Django 3.1.2 on 2020-10-31 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='dni',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='persona',
            name='nac',
            field=models.DateField(default=None),
        ),
    ]
