# Generated by Django 2.2.16 on 2020-11-04 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_auto_20201031_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='alta_sistema',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
