# Generated by Django 2.2.16 on 2020-11-11 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_persona_alta_sistema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='alta_sistema',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='domicilio',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='nac',
        ),
    ]
